baseURL = 'https://example.org/'
locale = 'ru-RU'
title = 'Usplit'
theme = 'introduction'

[params]
  themeStyle    = "auto"                                   # "light", "dark" или "auto"
  showMenu      = true
  fadeIn        = true
  favicon       = "favicon.png"
  customCSS     = ["css/tables.css", "css/buttons.css"]
  dateFormat    = "2 January 2006"
  email         = "karkachev2010@yandex.ru"
  description   = "Продажа, монтаж и сервисное обслуживание кондиционеров и вентиляции"

  [params.home]
    introHeight            = "fullheight"
    showLatest             = true
    showAllPosts           = false
    numberOfProjectsToShow = 3

  [params.projects]
    useTwoColumns = true

  [params.share]
    twitter   = false
    facebook  = false
    pinterest = false

  [[params.social]]
    url       = "mailto:karkachev2010@yandex.ru"
    icon      = "paper-plane"
    icon_pack = "fas"
  [[params.social]]
    url       = "tel:+79604777114"
    icon      = "phone"
    icon_pack = "fas"
  [[params.social]]
    url       = "https://wa.me/79604777114"
    icon      = "whatsapp"
    icon_pack = "fab"
  [[params.social]]
    url       = "https://t.me/+79604777114"
    icon      = "telegram"
    icon_pack = "fab"

[taxonomies]
  tag = "tags"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences  = true
    guessSyntax = false
    style       = "solarized-dark"
    tabWidth    = 4
